/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAiAssistantRouteImport } from './routes/_app.ai-assistant'
import { Route as AppAppUtilityRouteImport } from './routes/_app.app-utility'
import { Route as AppDrugsReferralsRouteImport } from './routes/_app.drugs-referrals'
import { Route as AppFacilityHrRouteImport } from './routes/_app.facility-hr'
import { Route as AppHrRouteImport } from './routes/_app.hr'
import { Route as AppObsHduRouteImport } from './routes/_app.obs-hdu'
import { Route as AppOutcomesRouteImport } from './routes/_app.outcomes'
import { Route as AppOverviewRouteImport } from './routes/_app.overview'
import { Route as AppReferralsRouteImport } from './routes/_app.referrals'
import { Route as AppReportsRouteImport } from './routes/_app.reports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAssistantRoute = AppAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAppUtilityRoute = AppAppUtilityRouteImport.update({
  id: '/app-utility',
  path: '/app-utility',
  getParentRoute: () => AppRoute,
} as any)
const AppDrugsReferralsRoute = AppDrugsReferralsRouteImport.update({
  id: '/drugs-referrals',
  path: '/drugs-referrals',
  getParentRoute: () => AppRoute,
} as any)
const AppFacilityHrRoute = AppFacilityHrRouteImport.update({
  id: '/facility-hr',
  path: '/facility-hr',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppObsHduRoute = AppObsHduRouteImport.update({
  id: '/obs-hdu',
  path: '/obs-hdu',
  getParentRoute: () => AppRoute,
} as any)
const AppOutcomesRoute = AppOutcomesRouteImport.update({
  id: '/outcomes',
  path: '/outcomes',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralsRoute = AppReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/app-utility': typeof AppAppUtilityRoute
  '/drugs-referrals': typeof AppDrugsReferralsRoute
  '/facility-hr': typeof AppFacilityHrRoute
  '/hr': typeof AppHrRoute
  '/obs-hdu': typeof AppObsHduRoute
  '/outcomes': typeof AppOutcomesRoute
  '/overview': typeof AppOverviewRoute
  '/referrals': typeof AppReferralsRoute
  '/reports': typeof AppReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/app-utility': typeof AppAppUtilityRoute
  '/drugs-referrals': typeof AppDrugsReferralsRoute
  '/facility-hr': typeof AppFacilityHrRoute
  '/hr': typeof AppHrRoute
  '/obs-hdu': typeof AppObsHduRoute
  '/outcomes': typeof AppOutcomesRoute
  '/overview': typeof AppOverviewRoute
  '/referrals': typeof AppReferralsRoute
  '/reports': typeof AppReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/ai-assistant': typeof AppAiAssistantRoute
  '/_app/app-utility': typeof AppAppUtilityRoute
  '/_app/drugs-referrals': typeof AppDrugsReferralsRoute
  '/_app/facility-hr': typeof AppFacilityHrRoute
  '/_app/hr': typeof AppHrRoute
  '/_app/obs-hdu': typeof AppObsHduRoute
  '/_app/outcomes': typeof AppOutcomesRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/referrals': typeof AppReferralsRoute
  '/_app/reports': typeof AppReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/ai-assistant'
    | '/app-utility'
    | '/drugs-referrals'
    | '/facility-hr'
    | '/hr'
    | '/obs-hdu'
    | '/outcomes'
    | '/overview'
    | '/referrals'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/ai-assistant'
    | '/app-utility'
    | '/drugs-referrals'
    | '/facility-hr'
    | '/hr'
    | '/obs-hdu'
    | '/outcomes'
    | '/overview'
    | '/referrals'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/ai-assistant'
    | '/_app/app-utility'
    | '/_app/drugs-referrals'
    | '/_app/facility-hr'
    | '/_app/hr'
    | '/_app/obs-hdu'
    | '/_app/outcomes'
    | '/_app/overview'
    | '/_app/referrals'
    | '/_app/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-assistant': {
      id: '/_app/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AppAiAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app-utility': {
      id: '/_app/app-utility'
      path: '/app-utility'
      fullPath: '/app-utility'
      preLoaderRoute: typeof AppAppUtilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drugs-referrals': {
      id: '/_app/drugs-referrals'
      path: '/drugs-referrals'
      fullPath: '/drugs-referrals'
      preLoaderRoute: typeof AppDrugsReferralsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/facility-hr': {
      id: '/_app/facility-hr'
      path: '/facility-hr'
      fullPath: '/facility-hr'
      preLoaderRoute: typeof AppFacilityHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr': {
      id: '/_app/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/obs-hdu': {
      id: '/_app/obs-hdu'
      path: '/obs-hdu'
      fullPath: '/obs-hdu'
      preLoaderRoute: typeof AppObsHduRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outcomes': {
      id: '/_app/outcomes'
      path: '/outcomes'
      fullPath: '/outcomes'
      preLoaderRoute: typeof AppOutcomesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/referrals': {
      id: '/_app/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AppReferralsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAiAssistantRoute: typeof AppAiAssistantRoute
  AppAppUtilityRoute: typeof AppAppUtilityRoute
  AppDrugsReferralsRoute: typeof AppDrugsReferralsRoute
  AppFacilityHrRoute: typeof AppFacilityHrRoute
  AppHrRoute: typeof AppHrRoute
  AppObsHduRoute: typeof AppObsHduRoute
  AppOutcomesRoute: typeof AppOutcomesRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppReferralsRoute: typeof AppReferralsRoute
  AppReportsRoute: typeof AppReportsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAiAssistantRoute: AppAiAssistantRoute,
  AppAppUtilityRoute: AppAppUtilityRoute,
  AppDrugsReferralsRoute: AppDrugsReferralsRoute,
  AppFacilityHrRoute: AppFacilityHrRoute,
  AppHrRoute: AppHrRoute,
  AppObsHduRoute: AppObsHduRoute,
  AppOutcomesRoute: AppOutcomesRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppReferralsRoute: AppReferralsRoute,
  AppReportsRoute: AppReportsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
